# Generated by Django 5.1 on 2024-08-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='created_by',
            new_name='username',
        ),
    ]
