# Generated by Django 5.1 on 2024-08-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_rename_created_by_customurl_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customurl',
            old_name='username',
            new_name='created_by',
        ),
    ]
