# Generated by Django 5.1 on 2024-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_rename_username_customurl_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
