# Generated by Django 5.1 on 2024-08-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_customurl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurl',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
