# Generated by Django 5.1 on 2024-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_customurl_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurl',
            name='one_time_only',
            field=models.BooleanField(default=False),
        ),
    ]
